# Generated by Django 2.2.7 on 2019-11-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('history', 'History'), ('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('biography', 'Biography')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='Book_Covers/'),
        ),
    ]
